var app=angular.module("mycal",[]);
	app.controller("calctrl",function($scope)
	{
	$scope.display="";
	$scope.input=function(val)
	{
		 $scope.display+=val;
	};
	$scope.op=function(op)
	{
		$scope.display+=op;
	};
	$scope.clear=function(c)
	{
		$scope.display="";
	};	
	$scope.e=function(e)
	{
	$scope.display=eval($scope.display);
	};
	})	